"""empty message

Revision ID: a7e19131e964
Revises: 037641295205
Create Date: 2020-10-31 04:33:59.723334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e19131e964'
down_revision = '037641295205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('past_shows', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'upcoming_shows')
    op.drop_column('venue', 'past_shows')
    # ### end Alembic commands ###
