"""version no:01

Revision ID: ab3396f53eed
Revises: a7e19131e964
Create Date: 2020-10-31 06:10:41.188908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3396f53eed'
down_revision = 'a7e19131e964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'upcoming_shows')
    op.drop_column('artist', 'past_shows')
    # ### end Alembic commands ###
